### ISSUE TITLE
run tfm fwu fail

### ISSUE THREAD

**Issue by thomas-coding** [emb-team/tfm-fwu#1]
Hi,

I refer to tfm-fwu guide:
https://emb-team.com/tf-m-fw-update-testing-on-qemu/

download and build  ok, but run fail, output log:
[INF] Starting bootloader
[INF] Swap type: none
[INF] Swap type: none
[ERR] Failed to add data to shared memory area.
[ERR] Unable to find bootable image

The following shell script is the complete process of download and execution. 
Is there anything wrong here?

Thanks.

#============================= shell begin =====================================
SHELL_FOLDER=$(cd "$(dirname "$0")";pwd)
BUILD_DIR=${SHELL_FOLDER}/test
PROJECTS_DIR=${BUILD_DIR}/projects
QEMU_DIR=${PROJECTS_DIR}/qemu-tfm
TFM_DIR=${PROJECTS_DIR}/tfm-fwu
FREERTOS_DIR=${PROJECTS_DIR}/freertos-tfm-fwu

#mkdir
mkdir ${BUILD_DIR}
mkdir ${PROJECTS_DIR}

#download
cd ${PROJECTS_DIR}
git clone https://github.com/emb-team/freertos-tfm-fwu.git --recurse-submodules
git clone https://github.com/emb-team/qemu-tfm
git clone https://github.com/emb-team/tfm-fwu

#build qemu
cd ${QEMU_DIR}
mkdir build
cd ${QEMU_DIR}/build
../configure
make -j8

#build tfm
cd ${TFM_DIR}
cmake -S . -B cmake_build -DTFM_PLATFORM=mps2/an521 -DTFM_TOOLCHAIN_FILE=toolchain_GNUARM.cmake
cmake --build cmake_build -- install

#build freerots
cd ${FREERTOS_DIR}/freertos_kernel/portable/ThirdParty/GCC/ARM_CM33_TFM
make

#build flash
cd ${TFM_DIR}
./sign.sh
gcc -g -o toflash toflash.c
./toflash

#run qemu
cd ${QEMU_DIR}
./build/qemu-system-arm -machine mps2-an521 -cpu cortex-m33 -kernel ${PROJECTS_DIR}/tfm-fwu/cmake_build/install/outputs/MPS2/AN521/bl2.elf -m 16 -nographic

#============================= shell end=====================================

**Comment by emb-team** [comment]
Hi,

Oh, yes I did change the following file in tfm:
cmake_build/lib/ext/mcuboot-src/boot/bootutil/src/loader.c
I commented out the following lines:
#ifdef MCUBOOT_DATA_SHARING
#if 0
        rc = boot_save_shared_data(boot_img_hdr(state, BOOT_PRIMARY_SLOT),
                                   BOOT_IMG_AREA(state, BOOT_PRIMARY_SLOT));
        if (rc != 0) {
            BOOT_LOG_ERR("Failed to add data to shared memory area.");
            goto out;
        }
#endif
#endif /* MCUBOOT_DATA_SHARING */

Shall work afterwards..

Best Regards,
Evgenii Zharkov


пт, 30 апр. 2021 г. в 08:32, thomas-coding ***@***.***>:

**Comment by thomas-coding** [comment]
ok, got it, thanks.
